server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: second-hand-car
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/second_hand_car?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.secondhandcar.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.secondhandcar.controller

# 文件上传路径配置
file:
  upload:
    path: ${user.home}/second_hand_car_uploads
    access-path: /uploads/**

# JWT配置
jwt:
  secret: UzajX0jyjf7w4kEP5jQyO63bwfvK9HUzajX0jyjf7w4kEP5jQyO63bwfvK9HUzajX0jyjf7w4kEP5jQyO63bwfvK9HUzajX0jyjf7w4kEP5jQyO63bwfvK9HUzajX0jyjf7w4kEP5jQyO63bwfvK9H
  expiration: 86400000  # 24小时 